light-component
Ilistratov/LostInTheDark pull request #26
Opened 2021-12-06 00:38 UTC by MonsterOnLeash

Created light component which sets lighted to true when lighted (walls are taken into account if tag Wall is applied to them). Walls can cast shadows. Sample point light prefab is added into prefabs folder (further adjustment of collider and range of light should be applied when sprites for other objects are added). Also added simple player-movement script for easier player interaction testing.

2021-12-06 19:39 UTC, Ilistratov requested changes

2021-12-06 19:39 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +            if (allObjectsBetween[i].collider.gameObject.CompareTag("Wall"))
На сколько я знаю, сейчас в Unity у объекта может быть только 1 тег.
Вполне вероятна ситуация, когда захочется для объекта, блокирующего свет, поюзать тек
для какой нибудь более осмысленной цели.

Вроде как в URP есть компонент [Shadow Caster 2D](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/2DShadows.html)
Который мы кажется anyway будем юзать, чтобы помечать, какие объекты отбрасывают тень
(это для визуальной части). Я предлагаю тут вместо тега проверять объект на наличие у него
этого компонента.

2021-12-06 19:39 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +    public bool lighted;
Я бы хотел поддерживать не бинарное состояние освещенности, а какое-нибудь значение
от 0 до 1, где 0 - полностью темно, 1 - полностью светло. Это значение на пример насчитывать как
sum for each reachable light: 1 / (distance to light)^2. Или еще как нибудь.

Ну или на крайняк сохранять куда-нибудь список источников света, которые нас освещают
и выдавать его.

2021-12-06 19:39 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +        if (collidedLights.Count != 0)
Разве `List<T>.ForEach(...)` не будет корректно работать для пустого списка?

2021-12-06 19:39 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +        if (collision.gameObject.CompareTag("Light"))
Ты точно хочешь использовать для этого тег?
У нас для каждого источника освещения скорее всего будет в
компонентах что-то вроде [Light2D](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.0/api/UnityEngine.Experimental.Rendering.Universal.Light2D.html).
Может стоит тут просто чекать объект на наличие этого компонента?

2021-12-06 19:39 UTC, Ilistratov commented on Assets/Scripts/PlayerMovementForTests.cs
> +public class PlayerMovementForTests : MonoBehaviour
А чем же тебе имеющийся PlayerController не угодил?)

2021-12-06 20:32 UTC, MonsterOnLeash commented on Assets/Scripts/PlayerMovementForTests.cs
> +public class PlayerMovementForTests : MonoBehaviour
Тот который был у меня на момент написания  не был полностью доработан, поэтому пришлось делать шаблон, да и в случае если надо будет какую-нибудь штуку отдельно потестить на предмете то проще будет когда оно уже умеет двигаться. Имхо имеет место быть

2021-12-06 20:34 UTC, MonsterOnLeash commented on Assets/Scripts/LightInteractor.cs
> +        if (collidedLights.Count != 0)
Не будет, кидает NullReferenceException

2021-12-06 21:17 UTC, MonsterOnLeash commented on Assets/Scripts/LightInteractor.cs
> +    public bool lighted;
Ну, список источников света итак есть в collidedLights.

2021-12-07 14:21 UTC, Ilistratov requested changes

2021-12-07 14:21 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +        lighted += 1/(distance * distance);
Тут стоит учесть, что у источника света есть intensity, на него стоит домножить.
Если distance < 1, то у тебя получится значение > 1. Нужно что-то вроде distance = min(distance, 1).

2021-12-07 14:21 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +                lighted = 0;
Тут баг.
Если до этого в lighted был не 0(тобишь ты уже нашел какие-то источники света, которые нас освещают)
А текущий нас не освещает, то ты говоришь, что теперь нас ничего не освещает, что не верно.

2021-12-07 14:21 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +    public float lighted;
`lighted` уже не совсем корректно отражает смысл этой переменной. Я бы подумал над именем получше.
lightLevel какой-нибудь там...

2021-12-08 16:41 UTC, Ilistratov approved these changes

2021-12-08 16:41 UTC, Ilistratov commented on Assets/Scripts/LightInteractor.cs
> +        lightLevel += 1/(distance * distance);
Эта строчка тут не нужна, заведи issue на ее удаление.

2021-12-08 16:41 UTC, merged